### PR TITLE
Add support for the conditional compile elements

### PR DESCRIPTION
**Pull request by evgygor**

### CODE REVIEW

**Comment by evgygor** [comment]
Thanks for your comments and remarks.
Starting to fix those issues.

**Comment by evgygor** [comment]
I fixed the whitespace issues and added tests for conditional compile blocks.

**Comment by TwitchBronBron** [comment]
Done. There were still a ton of whitespace issues in the main file (i.e. they were still indented with 2 spaces instead of 4), but I'll just fix them. Thanks for your contribution.

**Comment by evgygor** [comment]
> Done. There were still a ton of whitespace issues in the main file (i.e. they were still indented with 2 spaces instead of 4), but I'll just fix them. Thanks for your contribution.

Strange...
My default indentation is 4 spaces in all projects. Maybe is a formatter issue.
I'll check after the merge.

**Pull request merged**
